# Generated by Django 4.0.5 on 2023-08-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_rename_vehiculo_vehiculomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar_catalogo')]},
        ),
    ]
